[alias]
bweb = "build --target wasm32-unknown-unknown"
cli = "run --target x86_64-unknown-linux-gnu"
rcli = "run --release --target x86_64-unknown-linux-gnu"
bcli = "build --target x86_64-unknown-linux-gnu"
brcli = "build --release --target x86_64-unknown-linux-gnu"

[build]
target = "wasm32-unknown-unknown"

